---
title: "Download the files"
author: "Joris Muller"
date: "12/18/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '../.')
```

# Aim

Download the files

# Description

All the data files and the description file are available on [http://base-donnees-publique.medicaments.gouv.fr/telechargement.php](http://base-donnees-publique.medicaments.gouv.fr/telechargement.php).

Data files are *.txt*

Description file is *.pdf*

I will use `httr` to download all of them.

# Implementation

```{r}
url <- "http://base-donnees-publique.medicaments.gouv.fr/telechargement.php"
```

Get the page

```{r}
library(rvest)
library(XML)
page <- read_html(url)
```

Databases URL could be find with files ending by .txt

```{r}
dl_end_url <- page %>%
  html_nodes("#container ul a") %>%
  html_attr("href")

# avoid the PDF
data_end_url <- dl_end_url[-grep("pdf", dl_end_url)]

full_url <- function(endurl, base = url) {
  paste0(base, endurl)
}

filename <- function(endurl) {
  gsub("\\?fichier=", "", x= endurl)
}

file.create("raw_data/CIS_bdpm.txt")

lapply(data_end_url, function(x) download.file(url = full_url(x), destfile = file.path("raw_data", filename(x)))
  )
```

List the downloaded files 

```{r}
dir("raw_data")
```



